name: Release - Service
run-name: Push Service image

on:
  push:
    branches:
      - ci/service-image-building

jobs:
  test_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/checkout@v4
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          file: ./service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/authservice:latest
