name: Tests - Shared
run-name: Testing Shared package

on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - synchronize
    branches:
      - dev
    paths:
      - 'shared/**'
      - '.github/workflows/tests-shared.yml'
      - 'package.json'

jobs:
  tests:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Setup
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm i
      - name: Run tests
        run: npm -w shared run test
        env:
          REDIS_HOST: 'host'
          REDIS_PORT: 123
